### ISSUE TITLE
sealed-secrets chart version 2.0.2 is not deployable

### ISSUE THREAD

**Issue by aljorhythm** [digitalocean/Kubernetes-Starter-Kit-Developers#162]
image for 0.17.1 on quay.io will not be found
See https://github.com/bitnami-labs/sealed-secrets/issues/822

**Comment by v-bpastiu** [comment]
Hi, thanks for the contribution. We will test everything out and approve if everything works. Indeed the upgrade to sealed secrets helm chart was needed due to the image pulling error. We will come back to this. Thanks

**Comment by aljorhythm** [comment]
👍Thanks

**Comment by aljorhythm** [comment]
merged
